services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: perfume-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Salam123!@
    ports:
      - "1433:1433"
    networks:
      - perfume-net
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./back-end/Server
      dockerfile: Dockerfile
    image: perfume-backend:latest
    container_name: perfume-backend
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:5034
      - ConnectionStrings__Perfume_DB=Server=perfume-sql,1433;Database=PerfumeDB;User Id=sa;Password=Salam123!@;TrustServerCertificate=True;
    ports:
      - "5034:5034"
    networks:
      - perfume-net

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: perfume-frontend:latest
    container_name: perfume-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://perfume-backend:5034/api
    ports:
      - "3000:3000"
    networks:
      - perfume-net

networks:
  perfume-net:

volumes:
  mssql_data: